### ISSUE TITLE
ValueError: mutable default <class 'jaxlib.xla_extension.ArrayImpl'> for field current_player is not allowed: use default_factory

### ISSUE THREAD

**Issue by carlosgmartin** [sotetsuk/pgx#1062]
Example:

```
$ python3 -c "import pgx; pgx.make('2048')" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/pgx/v1.py", line 347, in make
    from pgx.play2048 import Play2048
  File "/usr/local/lib/python3.11/site-packages/pgx/play2048.py", line 27, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pgx/_src/struct.py", line 115, in dataclass
    data_clz = dataclasses.dataclass(frozen=True)(clz)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'jaxlib.xla_extension.ArrayImpl'> for field current_player is not allowed: use default_factory
```

Version information:
- macOS 11.7.10
- Python 3.11.5
- PGX 1.4.0

**Comment by sotetsuk** [comment]
Thank you for your comment.l! Currently Pgx only supports 3.8-3.10. python 3.11 is not supported.

**Comment by carlosgmartin** [comment]
@sotetsuk When will 3.11 / 3.12 be supported?

**Comment by sotetsuk** [comment]
At the moment, there are no specific plans or milestones for Python 3.11 support. We believe we can support it once the issues related to dataclass are resolved.

**Comment by carlosgmartin** [comment]
@sotetsuk To resolve this issue, would you be open to a PR that replaces
```
current_player: jnp.ndarray = jnp.int8(0)
```
with
```
current_player: jnp.ndarray = dataclasses.field(default_factory=lambda: jnp.int8(0))
```
and likewise for other fields, and possibly for other game classes too?

**Comment by sotetsuk** [comment]
Thank you for providing a solution. One concern is that by using the default factory, the initialization code is called not just the first time, but every time, so I'm worried about whether this will decrease the execution speed. I'm curious if JIT will optimize this.
